//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restart.Lingue {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
       
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restart.Lingue.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assegna / Riassegna spesa.
        /// </summary>
        internal static string A_R {
            get {
                return ResourceManager.GetString("A/R", resourceCulture);
            }
        }

        internal static string Abbigliamento
            {
            get
                {
                return ResourceManager.GetString ("Abbigliamento", resourceCulture);
                }
            }

        internal static string Salute
            {
            get
                {
                return ResourceManager.GetString ("Salute", resourceCulture);
                }
            }

        internal static string GestisciQuota
            {
            get
                {
                return ResourceManager.GetString ("GestisciQuota", resourceCulture);
                }
            }

        internal static string CategorieAggiuntive
            {
            get
                {
                return ResourceManager.GetString ("CategorieAggiuntive", resourceCulture);
                }
            }

        internal static string SpeseIeri
            {
            get
                {
                return ResourceManager.GetString ("SpeseIeri", resourceCulture);
                }
            }


        internal static string SpeseOggi
            {
            get
                {
                return ResourceManager.GetString ("SpeseOggi", resourceCulture);
                }
            }


        internal static string SpesaDaSostenere
            {
            get
                {
                return ResourceManager.GetString ("SpesaDaSostenere", resourceCulture);
                }
            }

        internal static string RisparmiRimanente
            {
            get
                {
                return ResourceManager.GetString ("RisparmiRimanente", resourceCulture);
                }
            }

        internal static string Mensile
            {
            get
                {
                return ResourceManager.GetString ("Mensile", resourceCulture);
                }
            }

        internal static string Giornaliera
            {
            get
                {
                return ResourceManager.GetString ("Giornaliera", resourceCulture);
                }
            }

        internal static string AScelta
            {
            get
                {
                return ResourceManager.GetString ("AScelta", resourceCulture);
                }
            }
        



             internal static string Localizzazione
            {
            get
                {
                return ResourceManager.GetString ("Localizzazione", resourceCulture);
                }
            }

        internal static string Salva
            {
            get
                {
                return ResourceManager.GetString ("Salva", resourceCulture);
                }
            }


        internal static string Orario
            {
            get
                {
                return ResourceManager.GetString ("Orario", resourceCulture);
                }
            }

        internal static string Rimanenza
            {
            get
                {
                return ResourceManager.GetString ("Rimanenza", resourceCulture);
                }
            }

        internal static string TettoSpesa
            {
            get
                {
                return ResourceManager.GetString ("TettoSpesa", resourceCulture);
                }
            }

        internal static string GiorniRimanenti
            {
            get
                {
                return ResourceManager.GetString ("GiorniRimanenti", resourceCulture);
                }
            }

        internal static string DataScadenza
            {
            get
                {
                return ResourceManager.GetString ("DataScadenza", resourceCulture);
                }
            }


        internal static string AttivaMappa
            {
            get
                {
                return ResourceManager.GetString ("AttivaMappa", resourceCulture);
                }
            }

        /// <summary>
        ///   Looks up a localized string similar to Aggiungi un risparmio.
        /// </summary>
        internal static string AGGIUNGI_RISPARMIO {
            get {
                return ResourceManager.GetString("AGGIUNGI_RISPARMIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altro.
        /// </summary>
        internal static string Altro {
            get {
                return ResourceManager.GetString("Altro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        internal static string ANNULLA {
            get {
                return ResourceManager.GetString("ANNULLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistenza.
        /// </summary>
        internal static string ASSISTENZA {
            get {
                return ResourceManager.GetString("ASSISTENZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azzera filtri.
        /// </summary>
        internal static string AZZERA {
            get {
                return ResourceManager.GetString("AZZERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bellezza.
        /// </summary>
        internal static string Bellezza {
            get {
                return ResourceManager.GetString("Bellezza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosa vuoi cambiare?.
        /// </summary>
        internal static string CAMBIARE {
            get {
                return ResourceManager.GetString("CAMBIARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuoi cambiare ancora qualcosa?.
        /// </summary>
        internal static string CAMBIARE_ANCORA {
            get {
                return ResourceManager.GetString("CAMBIARE_ANCORA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancella.
        /// </summary>
        internal static string CANCELLA {
            get {
                return ResourceManager.GetString("CANCELLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        internal static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● {0:F3}.
        /// </summary>
        internal static string Categoria_Display {
            get {
                return ResourceManager.GetString("Categoria_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cibo.
        /// </summary>
        internal static string Cibo {
            get {
                return ResourceManager.GetString("Cibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cifra:.
        /// </summary>
        internal static string CIFRA {
            get {
                return ResourceManager.GetString("CIFRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci una cifra corretta!.
        /// </summary>
        internal static string CIFRA_CORRETTA {
            get {
                return ResourceManager.GetString("CIFRA_CORRETTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cifra non corretta!.
        /// </summary>
        internal static string CIFRA_NON {
            get {
                return ResourceManager.GetString("CIFRA_NON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cifra non ammessa!.
        /// </summary>
        internal static string CIFRA_NON_A {
            get {
                return ResourceManager.GetString("CIFRA_NON_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complimenti hai risparmiato ben .
        /// </summary>
        internal static string COMPLIMENTI {
            get {
                return ResourceManager.GetString("COMPLIMENTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma.
        /// </summary>
        internal static string CONFERMA {
            get {
                return ResourceManager.GetString("CONFERMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosa vuoi fare?.
        /// </summary>
        internal static string COSA {
            get {
                return ResourceManager.GetString("COSA", resourceCulture);
            }
        }

        internal static string EmailInviata
            {
            get
                {
                return ResourceManager.GetString ("EmailInviata", resourceCulture);
                }
            }

        /// <summary>
        ///   Looks up a localized string similar to Cultura.
        /// </summary>
        internal static string Cultura {
            get {
                return ResourceManager.GetString("Cultura", resourceCulture);
            }
        }

        internal static string InserisciDatiCorretti
            {
            get
                {
                return ResourceManager.GetString ("InserisciDatiCorretti", resourceCulture);
                }
            }

        internal static string NoConnessione
            {
            get
                {
                return ResourceManager.GetString ("NoConnessione", resourceCulture);
                }
            }

        internal static string Caratteri
            {
            get
                {
                return ResourceManager.GetString ("Caratteri", resourceCulture);
                }
            }

        internal static string AccountNonPresente
            {
            get
                {
                return ResourceManager.GetString ("AccountNonPresente", resourceCulture);
                }
            }

        internal static string LogOut
            {
            get
                {
                return ResourceManager.GetString ("LogOut", resourceCulture);
                }
            }




        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string DATA {
            get {
                return ResourceManager.GetString("DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divertimenti.
        /// </summary>
        internal static string Divertimenti {
            get {
                return ResourceManager.GetString("Divertimenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fai una donazione.
        /// </summary>
        internal static string DONAZIONE {
            get {
                return ResourceManager.GetString("DONAZIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edita la spesa.
        /// </summary>
        internal static string EDITA {
            get {
                return ResourceManager.GetString("EDITA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica il risparmio.
        /// </summary>
        internal static string EDITA_RISPRAMIO {
            get {
                return ResourceManager.GetString("EDITA_RISPRAMIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina.
        /// </summary>
        internal static string ELIMINA {
            get {
                return ResourceManager.GetString("ELIMINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina il risparmio.
        /// </summary>
        internal static string ELIMINA_RISPARMIO {
            get {
                return ResourceManager.GetString("ELIMINA_RISPARMIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina la spesa.
        /// </summary>
        internal static string ELIMINA_SPESA {
            get {
                return ResourceManager.GetString("ELIMINA_SPESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtra.
        /// </summary>
        internal static string FILTRA {
            get {
                return ResourceManager.GetString("FILTRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giorni .
        /// </summary>
        internal static string GIORNI {
            get {
                return ResourceManager.GetString("GIORNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostazioni.
        /// </summary>
        internal static string IMPOSTAZIONI {
            get {
                return ResourceManager.GetString("IMPOSTAZIONI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indietro.
        /// </summary>
        internal static string INDIETRO {
            get {
                return ResourceManager.GetString("INDIETRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglese.
        /// </summary>
        internal static string INGLESE {
            get {
                return ResourceManager.GetString("INGLESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci una categoria!.
        /// </summary>
        internal static string INSERISCI_CATEGORIA {
            get {
                return ResourceManager.GetString("INSERISCI_CATEGORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci una cifra!.
        /// </summary>
        internal static string INSERISCI_CIFRA {
            get {
                return ResourceManager.GetString("INSERISCI_CIFRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci una quota:.
        /// </summary>
        internal static string INSERISCI_QUOTA {
            get {
                return ResourceManager.GetString("INSERISCI_QUOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci la somma del tuo risparmio.
        /// </summary>
        internal static string INSERISCI_SRISPARMIO {
            get {
                return ResourceManager.GetString("INSERISCI_SRISPARMIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Istruzione.
        /// </summary>
        internal static string Istruzione {
            get {
                return ResourceManager.GetString("Istruzione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano.
        /// </summary>
        internal static string ITALIANO {
            get {
                return ResourceManager.GetString("ITALIANO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia lingua.
        /// </summary>
        internal static string LINGUA {
            get {
                return ResourceManager.GetString("LINGUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica il risparmio.
        /// </summary>
        internal static string MODIFICA_RISPARMIO {
            get {
                return ResourceManager.GetString("MODIFICA_RISPARMIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non puoi inserire una data precedente ad oggi!.
        /// </summary>
        internal static string NO_DATA {
            get {
                return ResourceManager.GetString("NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non puoi più inserire spese!.
        /// </summary>
        internal static string NON {
            get {
                return ResourceManager.GetString("NON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota.
        /// </summary>
        internal static string NOTA {
            get {
                return ResourceManager.GetString("NOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota:.
        /// </summary>
        internal static string NOTA_ {
            get {
                return ResourceManager.GetString("NOTA:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuova categoria.
        /// </summary>
        internal static string NUOVA_CATEGORIA {
            get {
                return ResourceManager.GetString("NUOVA_CATEGORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica la nota.
        /// </summary>
        internal static string NUOVA_NOTA {
            get {
                return ResourceManager.GetString("NUOVA_NOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuova somma.
        /// </summary>
        internal static string NUOVA_SOMMA {
            get {
                return ResourceManager.GetString("NUOVA_SOMMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci una nuova somma per la tua quota.
        /// </summary>
        internal static string NUOVA_SOMMA_QUOTA {
            get {
                return ResourceManager.GetString("NUOVA_SOMMA_QUOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordina per.
        /// </summary>
        internal static string ORDINA {
            get {
                return ResourceManager.GetString("ORDINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puoi inserire una nota.
        /// </summary>
        internal static string PUOI_NOTA {
            get {
                return ResourceManager.GetString("PUOI_NOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUOTA:.
        /// </summary>
        internal static string QUOTA {
            get {
                return ResourceManager.GetString("QUOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hai raggiunto la tua quota!.
        /// </summary>
        internal static string QUOTA_RAGGIUNTA {
            get {
                return ResourceManager.GetString("QUOTA_RAGGIUNTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regali.
        /// </summary>
        internal static string Regali {
            get {
                return ResourceManager.GetString("Regali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segna come effettuata.
        /// </summary>
        internal static string SEGNA {
            get {
                return ResourceManager.GetString("SEGNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona il tipo di spesa.
        /// </summary>
        internal static string SELEZIONA_SPESA {
            get {
                return ResourceManager.GetString("SELEZIONA_SPESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somma.
        /// </summary>
        internal static string SOMMA {
            get {
                return ResourceManager.GetString("SOMMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F2} €.
        /// </summary>
        internal static string Somma_Display {
            get {
                return ResourceManager.GetString("Somma_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spagnolo.
        /// </summary>
        internal static string SPAGNOLO {
            get {
                return ResourceManager.GetString("SPAGNOLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spesa da effettuare.
        /// </summary>
        internal static string SPESA_DAEFFETTUARE {
            get {
                return ResourceManager.GetString("SPESA_DAEFFETTUARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spesa effettuata.
        /// </summary>
        internal static string SPESA_EFFETTUATA {
            get {
                return ResourceManager.GetString("SPESA_EFFETTUATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spesa più alta: {0:F2} €.
        /// </summary>
        internal static string Spesa_Massima {
            get {
                return ResourceManager.GetString("Spesa_Massima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistiche.
        /// </summary>
        internal static string STATISTICHE {
            get {
                return ResourceManager.GetString("STATISTICHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia tema.
        /// </summary>
        internal static string TEMA {
            get {
                return ResourceManager.GetString("TEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTALE: {0:F2} €.
        /// </summary>
        internal static string Totale {
            get {
                return ResourceManager.GetString("Totale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trasporti.
        /// </summary>
        internal static string Trasporti {
            get {
                return ResourceManager.GetString("Trasporti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to € .
        /// </summary>
        internal static string VALUTA {
            get {
                return ResourceManager.GetString("VALUTA", resourceCulture);
            }
        }

        internal static string QuotaMensile
            {
            get
                {
                return ResourceManager.GetString ("QuotaMensile", resourceCulture);
                }
            }
        internal static string QuotaLibera
            {
            get
                {
                return ResourceManager.GetString ("QuotaLibera", resourceCulture);
                }
            }
        internal static string Oggi
            {
            get
                {
                return ResourceManager.GetString ("Oggi", resourceCulture);
                }
            }
        internal static string Ieri
            {
            get
                {
                return ResourceManager.GetString ("Ieri", resourceCulture);
                }
            }
        internal static string Risparmio
            {
            get
                {
                return ResourceManager.GetString ("Risparmio", resourceCulture);
                }
            }

        internal static string Quanto
            {
            get
                {
                return ResourceManager.GetString ("Quanto", resourceCulture);
                }
            }

        internal static string Dona
            {
            get
                {
                return ResourceManager.GetString ("Dona", resourceCulture);
                }
            }

        internal static string MessaggioDonazione
            {
            get
                {
                return ResourceManager.GetString ("MessaggioDonazione", resourceCulture);
                }
            }

        internal static string NumeroSpese
            {
            get
                {
                return ResourceManager.GetString ("NumeroSpese", resourceCulture);
                }
            }

        internal static string SpesaMassima
            {
            get
                {
                return ResourceManager.GetString ("SpesaMassima", resourceCulture);
                }
            }

        internal static string SpeseMese
            {
            get
                {
                return ResourceManager.GetString ("SpeseMese", resourceCulture);
                }
            }

        internal static string SpeseMesePrecedente
            {
            get
                {
                return ResourceManager.GetString ("SpeseMesePrecedente", resourceCulture);
                }
            }

        internal static string SpeseSettimana
            {
            get
                {
                return ResourceManager.GetString ("SpeseSettimana", resourceCulture);
                }
            }

        internal static string Hey
            {
            get
                {
                return ResourceManager.GetString ("Hey", resourceCulture);
                }
            }

        internal static string Ricordati
            {
            get
                {
                return ResourceManager.GetString ("Ricordati", resourceCulture);
                }
            }

        internal static string BudgetOggi
            {
            get
                {
                return ResourceManager.GetString ("BudgetOggi", resourceCulture);
                }
            }

        internal static string TotaleQuestoMese
            {
            get
                {
                return ResourceManager.GetString ("TotaleQuestoMese", resourceCulture);
                }
            }

        internal static string Rimanente
            {
            get
                {
                return ResourceManager.GetString ("Rimanente", resourceCulture);
                }
            }

        internal static string ModificaRisparmio
            {
            get
                {
                return ResourceManager.GetString ("ModificaRisparmio", resourceCulture);
                }
            }

        internal static string QuotaScaduta
            {
            get
                {
                return ResourceManager.GetString ("QuotaScaduta", resourceCulture);
                }
            }
        internal static string MeseProssimo
            {
            get
                {
                return ResourceManager.GetString ("MeseProssimo", resourceCulture);
                }
            }
        internal static string QuotaRaggiunta
            {
            get
                {
                return ResourceManager.GetString ("QuotaRaggiunta", resourceCulture);
                }
            }
        internal static string Errore
            {
            get
                {
                return ResourceManager.GetString ("Errore", resourceCulture);
                }
            }
        internal static string NoSupporto
            {
            get
                {
                return ResourceManager.GetString ("NoSupporto", resourceCulture);
                }
            }
        internal static string NoAttivato
            {
            get
                {
                return ResourceManager.GetString ("NoAttivato", resourceCulture);
                }
            }
        internal static string NoPermessi
            {
            get
                {
                return ResourceManager.GetString ("NoPermessi", resourceCulture);
                }
            }
        internal static string NonTrovo
            {
            get
                {
                return ResourceManager.GetString ("NonTrovo", resourceCulture);
                }
            }
        internal static string Categorie
            {
            get
                {
                return ResourceManager.GetString ("Categorie", resourceCulture);
                }
            }
        internal static string Lingue
            {
            get
                {
                return ResourceManager.GetString ("Lingue", resourceCulture);
                }
            }


              internal static string Autenticazione
            {
            get
                {
                return ResourceManager.GetString ("Autenticazione", resourceCulture);
                }

            }

        internal static string ErroreAutenticazione
            {
            get
                {
                return ResourceManager.GetString ("ErroreAutenticazione", resourceCulture);
                }
            }

        internal static string Accedi
            {
            get
                {
                return ResourceManager.GetString ("Accedi", resourceCulture);
                }
            }

        internal static string AutenticazioneFallita
            {
            get
                {
                return ResourceManager.GetString ("AutenticazioneFallita", resourceCulture);
                }
            }

        internal static string Sblocco
            {
            get
                {
                return ResourceManager.GetString ("Sblocco", resourceCulture);
                }
            }

        internal static string RegistraSpese
            {
            get
                {
                return ResourceManager.GetString ("RegistraSpese", resourceCulture);
                }
            }


        internal static string FissaQuota
            {
            get
                {
                return ResourceManager.GetString ("FissaQuota", resourceCulture);
                }
            }

        internal static string GestisciRisparmi
            {
            get
                {
                return ResourceManager.GetString ("GestisciRisparmi", resourceCulture);
                }
            }

        internal static string Inizia
            {
            get
                {
                return ResourceManager.GetString ("Inizia", resourceCulture);
                }
            }

        internal static string Esci
            {
            get
                {
                return ResourceManager.GetString ("Esci", resourceCulture);
                }
            }

        internal static string SpesaAssegnata
            {
            get
                {
                return ResourceManager.GetString ("SpesaAssegnata", resourceCulture);
                }
            }

        internal static string Codice
            {
            get
                {
                return ResourceManager.GetString ("Codice", resourceCulture);
                }
            }

        internal static string EmailValida
            {
            get
                {
                return ResourceManager.GetString ("EmailValida", resourceCulture);
                }
            }

        internal static string CredenzialiErrate
            {
            get
                {
                return ResourceManager.GetString ("CredenzialiErrate", resourceCulture);
                }
            }
        internal static string AccountEsistente
            {
            get
                {
                return ResourceManager.GetString ("AccountEsistente", resourceCulture);
                }
            }

        internal static string DatiNonCorretti
            {
            get
                {
                return ResourceManager.GetString ("DatiNonCorretti", resourceCulture);
                }
            }

        internal static string PasswordDimenticata
            {
            get
                {
                return ResourceManager.GetString ("PasswordDimenticata", resourceCulture);
                }
            }

        internal static string Registrazione
            {
            get
                {
                return ResourceManager.GetString ("Registrazione", resourceCulture);
                }
            }

        internal static string ConfermaPassword
            {
            get
                {
                return ResourceManager.GetString ("ConfermaPassword", resourceCulture);
                }
            }

        internal static string MostraPassword
            {
            get
                {
                return ResourceManager.GetString ("MostraPassword", resourceCulture);
                }
            }


        internal static string RichiestePassword
            {
            get
                {
                return ResourceManager.GetString ("RichiestePassword", resourceCulture);
                }
            }


        internal static string CMaiuscolo
            {
            get
                {
                return ResourceManager.GetString ("CMaiuscolo", resourceCulture);
                }
            }

        internal static string Numero
            {
            get
                {
                return ResourceManager.GetString ("Numero", resourceCulture);
                }
            }



        internal static string CSpeciale
            {
            get
                {
                return ResourceManager.GetString ("CSpeciale", resourceCulture);
                }
            }

        internal static string InserisciCodice
            {
            get
                {
                return ResourceManager.GetString ("InserisciCodice", resourceCulture);
                }
            }




        internal static string Invia
            {
            get
                {
                return ResourceManager.GetString ("Invia", resourceCulture);
                }
            }

        internal static string InserisciDatiRegistrazione
            {
            get
                {
                return ResourceManager.GetString ("InserisciDatiRegistrazione", resourceCulture);
                }
            }


        internal static string IndirizzoValido
            {
            get
                {
                return ResourceManager.GetString ("IndirizzoValido", resourceCulture);
                }
            }








        }
    }
